<?php
define( 'LOGGED_IN_AS_CUSTOMER', 1 );
define( 'LOGGED_IN_AS_PRODUCTION_MANAGER', 2 );
define( 'LOGGED_IN_AS_FRONT_DESK_OFFICER', 3 );
define( 'LOGGED_IN_AS_MEMBER_OF_STAFF', 4 );

define( 'INDEX_OF_FIRST_ROW', 0 );
define( 'NO_ROW_FOUND', NULL );

define( 'LINE_NUMBER_OF_LINE_WHERE_FIRST_NAME_IS_STORED', 1 );
define( 'LINE_NUMBER_OF_LINE_WHERE_LAST_NAME_IS_STORED', 2 );
define( 'LINE_NUMBER_OF_LINE_WHERE_PASSWORD_IS_STORED', 3 );
define( 'NUMBER_OF_TABS_AFTER_EACH_COLUMN', 3 );

define( 'MAXIMUM_NUMBER_OF_PRINT_JOBS_THAT_SHOULD_BE_DISPLAYED', 10 );
define( 'MAXIMUM_NUMBER_OF_SUBTASKS_THAT_SHOULD_BE_DISPLAYED', 10 );

define( 'TIME_1_IS_EARLIER', 1 );
define( 'TIME_2_IS_EARLIER', 2 );
define( 'TIME_1_AND_TIME_2_ARE_EQUAL', 3 );
?>